sudo: false
dist: xenial
services:
  - docker

language: python

python: 3.6

before_install:
  - docker-compose -v
  - docker -v

install:
    - pip install -r backend/requirements.txt
    - pip install pytest
    - pip install coveralls
    - pip install tox

script:
    - coverage run --omit="*/templates*,*/venv*,*/tests*,*/python*" -m py.test

after_success:
    - coveralls
