sudo: false
dist: xenial
services:
  - postgresql

language: python

python: 3.6

install:
    - pip install -r backend/requirements.txt
    - pip install coveralls

before_script:
    - psql -c 'create database shurly;' -U postgres

script:
    - coverage run --omit="*/templates*,*/venv*,*/tests*,*/python*" backend/manage.py test

after_success:
    - coveralls
