sudo: false
dist: xenial
services:
  - docker

language: python

python: 3.6

before_install:
  - docker-compose -v
  - docker -v

install:
    - pip install coveralls

before_script:
    - docker-compose up --build -d

script:
    - coverage run --omit="*/templates*,*/venv*,*/tests*,*/python*" manage.py test

after_script:
    - docker-compose down

after_success:
    - coveralls
